version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  lint:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          terraform_version: "1.2"
      - terraform/fmt

  test:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          terraform_version: "1.2"
      - terraform/validate

workflows:
  version: 2
  lint:
    jobs:
      - lint

  test:
    jobs:
      - test
